version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: quotekeeper_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: quotekeeper
    ports:
      - "5432:5432"
    volumes:
      - quotekeeper_postgres_data:/var/lib/postgresql/data

volumes:
  quotekeeper_postgres_data:
